module.exports = [{
  "user_id": 606601420,
  "screen_name": "Advanced",
  "first_name": "Judy",
  "family_name": "Moore",
  "image": "https://robohash.org/fugaquiadolores.jpg?size=50x50&set=set1",
  "passive": false,
  "aggressive": false,
  "apology": true,
  "demon_mode": true
}, {
  "user_id": 849127193,
  "screen_name": "throughput",
  "first_name": "Raymond",
  "family_name": "Flores",
  "image": "https://robohash.org/estquisquamsit.png?size=50x50&set=set1",
  "passive": false,
  "aggressive": false,
  "apology": false,
  "demon_mode": true
}, {
  "user_id": 51851113,
  "screen_name": "architecture",
  "first_name": "Julie",
  "family_name": "Snyder",
  "image": "https://robohash.org/eumrerumut.bmp?size=50x50&set=set1",
  "passive": false,
  "aggressive": false,
  "apology": false,
  "demon_mode": true
}, {
  "user_id": 263551503,
  "screen_name": "help-desk",
  "first_name": "Frances",
  "family_name": "Watson",
  "image": "https://robohash.org/consequunturenimtempora.png?size=50x50&set=set1",
  "passive": true,
  "aggressive": false,
  "apology": true,
  "demon_mode": false
}, {
  "user_id": 757789724,
  "screen_name": "Upgradable",
  "first_name": "Kimberly",
  "family_name": "Hawkins",
  "image": "https://robohash.org/utautut.bmp?size=50x50&set=set1",
  "passive": true,
  "aggressive": false,
  "apology": false,
  "demon_mode": true
}, {
  "user_id": 349869264,
  "screen_name": "analyzing",
  "first_name": "Joe",
  "family_name": "Jones",
  "image": "https://robohash.org/autvoluptatumrepudiandae.jpg?size=50x50&set=set1",
  "passive": true,
  "aggressive": true,
  "apology": true,
  "demon_mode": true
}, {
  "user_id": 1236620,
  "screen_name": "Mandatory",
  "first_name": "Rachel",
  "family_name": "Fernandez",
  "image": "https://robohash.org/abenimatque.png?size=50x50&set=set1",
  "passive": true,
  "aggressive": false,
  "apology": false,
  "demon_mode": false
}, {
  "user_id": 35630854,
  "screen_name": "zero tolerance",
  "first_name": "Kathryn",
  "family_name": "Mendoza",
  "image": "https://robohash.org/atquecumlabore.bmp?size=50x50&set=set1",
  "passive": false,
  "aggressive": false,
  "apology": false,
  "demon_mode": true
}, {
  "user_id": 428250173,
  "screen_name": "Up-sized",
  "first_name": "Rachel",
  "family_name": "Mitchell",
  "image": "https://robohash.org/autiureerror.png?size=50x50&set=set1",
  "passive": false,
  "aggressive": true,
  "apology": true,
  "demon_mode": false
}, {
  "user_id": 372673021,
  "screen_name": "global",
  "first_name": "Sarah",
  "family_name": "Perez",
  "image": "https://robohash.org/estducimussunt.bmp?size=50x50&set=set1",
  "passive": false,
  "aggressive": true,
  "apology": true,
  "demon_mode": true
}]